/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SimSsoRouteImport } from './routes/sim-sso'
import { Route as SimRunnerRouteImport } from './routes/sim-runner'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as MinistryMapRouteImport } from './routes/ministry-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FraudDetectionRouteImport } from './routes/fraud-detection'
import { Route as FaceScanRouteImport } from './routes/face-scan'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CompanyPageRouteImport } from './routes/company-page'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CitizenPageRouteImport } from './routes/citizen-page'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApiGatewayRouteImport } from './routes/api-gateway'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SimSsoRoute = SimSsoRouteImport.update({
  id: '/sim-sso',
  path: '/sim-sso',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRunnerRoute = SimRunnerRouteImport.update({
  id: '/sim-runner',
  path: '/sim-runner',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryMapRoute = MinistryMapRouteImport.update({
  id: '/ministry-map',
  path: '/ministry-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudDetectionRoute = FraudDetectionRouteImport.update({
  id: '/fraud-detection',
  path: '/fraud-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceScanRoute = FaceScanRouteImport.update({
  id: '/face-scan',
  path: '/face-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPageRoute = CompanyPageRouteImport.update({
  id: '/company-page',
  path: '/company-page',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenPageRoute = CitizenPageRouteImport.update({
  id: '/citizen-page',
  path: '/citizen-page',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/citizen-page': typeof CitizenPageRoute
  '/command-center': typeof CommandCenterRoute
  '/company-page': typeof CompanyPageRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/login': typeof LoginRoute
  '/ministry-map': typeof MinistryMapRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sim-runner': typeof SimRunnerRoute
  '/sim-sso': typeof SimSsoRoute
  '/simulation': typeof SimulationRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/citizen-page': typeof CitizenPageRoute
  '/command-center': typeof CommandCenterRoute
  '/company-page': typeof CompanyPageRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/login': typeof LoginRoute
  '/ministry-map': typeof MinistryMapRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sim-runner': typeof SimRunnerRoute
  '/sim-sso': typeof SimSsoRoute
  '/simulation': typeof SimulationRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/citizen-page': typeof CitizenPageRoute
  '/command-center': typeof CommandCenterRoute
  '/company-page': typeof CompanyPageRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/login': typeof LoginRoute
  '/ministry-map': typeof MinistryMapRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/sim-runner': typeof SimRunnerRoute
  '/sim-sso': typeof SimSsoRoute
  '/simulation': typeof SimulationRoute
  '/verify': typeof VerifyRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/citizen-page'
    | '/command-center'
    | '/company-page'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/login'
    | '/ministry-map'
    | '/roles'
    | '/security'
    | '/services'
    | '/sim-runner'
    | '/sim-sso'
    | '/simulation'
    | '/verify'
    | '/dashboard/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/citizen-page'
    | '/command-center'
    | '/company-page'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/login'
    | '/ministry-map'
    | '/roles'
    | '/security'
    | '/services'
    | '/sim-runner'
    | '/sim-sso'
    | '/simulation'
    | '/verify'
    | '/dashboard/$role'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/citizen-page'
    | '/command-center'
    | '/company-page'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/login'
    | '/ministry-map'
    | '/roles'
    | '/security'
    | '/services'
    | '/sim-runner'
    | '/sim-sso'
    | '/simulation'
    | '/verify'
    | '/dashboard/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  CitizenRoute: typeof CitizenRoute
  CitizenPageRoute: typeof CitizenPageRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CompanyPageRoute: typeof CompanyPageRoute
  EventsRoute: typeof EventsRoute
  FaceScanRoute: typeof FaceScanRoute
  FraudDetectionRoute: typeof FraudDetectionRoute
  LoginRoute: typeof LoginRoute
  MinistryMapRoute: typeof MinistryMapRoute
  RolesRoute: typeof RolesRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SimRunnerRoute: typeof SimRunnerRoute
  SimSsoRoute: typeof SimSsoRoute
  SimulationRoute: typeof SimulationRoute
  VerifyRoute: typeof VerifyRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim-sso': {
      id: '/sim-sso'
      path: '/sim-sso'
      fullPath: '/sim-sso'
      preLoaderRoute: typeof SimSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim-runner': {
      id: '/sim-runner'
      path: '/sim-runner'
      fullPath: '/sim-runner'
      preLoaderRoute: typeof SimRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry-map': {
      id: '/ministry-map'
      path: '/ministry-map'
      fullPath: '/ministry-map'
      preLoaderRoute: typeof MinistryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-detection': {
      id: '/fraud-detection'
      path: '/fraud-detection'
      fullPath: '/fraud-detection'
      preLoaderRoute: typeof FraudDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-scan': {
      id: '/face-scan'
      path: '/face-scan'
      fullPath: '/face-scan'
      preLoaderRoute: typeof FaceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-page': {
      id: '/company-page'
      path: '/company-page'
      fullPath: '/company-page'
      preLoaderRoute: typeof CompanyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-page': {
      id: '/citizen-page'
      path: '/citizen-page'
      fullPath: '/citizen-page'
      preLoaderRoute: typeof CitizenPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-gateway': {
      id: '/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  CitizenRoute: CitizenRoute,
  CitizenPageRoute: CitizenPageRoute,
  CommandCenterRoute: CommandCenterRoute,
  CompanyPageRoute: CompanyPageRoute,
  EventsRoute: EventsRoute,
  FaceScanRoute: FaceScanRoute,
  FraudDetectionRoute: FraudDetectionRoute,
  LoginRoute: LoginRoute,
  MinistryMapRoute: MinistryMapRoute,
  RolesRoute: RolesRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SimRunnerRoute: SimRunnerRoute,
  SimSsoRoute: SimSsoRoute,
  SimulationRoute: SimulationRoute,
  VerifyRoute: VerifyRoute,
  DashboardRoleRoute: DashboardRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
