/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyStatusRouteImport } from './routes/verify-status'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ThreatMonitoringRouteImport } from './routes/threat-monitoring'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FraudDetectionRouteImport } from './routes/fraud-detection'
import { Route as FaceScanRouteImport } from './routes/face-scan'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApiGatewayRouteImport } from './routes/api-gateway'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'

const VerifyStatusRoute = VerifyStatusRouteImport.update({
  id: '/verify-status',
  path: '/verify-status',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatMonitoringRoute = ThreatMonitoringRouteImport.update({
  id: '/threat-monitoring',
  path: '/threat-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudDetectionRoute = FraudDetectionRouteImport.update({
  id: '/fraud-detection',
  path: '/fraud-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceScanRoute = FaceScanRouteImport.update({
  id: '/face-scan',
  path: '/face-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/simulation': typeof SimulationRoute
  '/threat-monitoring': typeof ThreatMonitoringRoute
  '/verify': typeof VerifyRoute
  '/verify-status': typeof VerifyStatusRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/simulation': typeof SimulationRoute
  '/threat-monitoring': typeof ThreatMonitoringRoute
  '/verify': typeof VerifyRoute
  '/verify-status': typeof VerifyStatusRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/citizen': typeof CitizenRoute
  '/command-center': typeof CommandCenterRoute
  '/events': typeof EventsRoute
  '/face-scan': typeof FaceScanRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/simulation': typeof SimulationRoute
  '/threat-monitoring': typeof ThreatMonitoringRoute
  '/verify': typeof VerifyRoute
  '/verify-status': typeof VerifyStatusRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/command-center'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/help'
    | '/login'
    | '/security'
    | '/services'
    | '/simulation'
    | '/threat-monitoring'
    | '/verify'
    | '/verify-status'
    | '/dashboard/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/command-center'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/help'
    | '/login'
    | '/security'
    | '/services'
    | '/simulation'
    | '/threat-monitoring'
    | '/verify'
    | '/verify-status'
    | '/dashboard/$role'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-gateway'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/citizen'
    | '/command-center'
    | '/events'
    | '/face-scan'
    | '/fraud-detection'
    | '/help'
    | '/login'
    | '/security'
    | '/services'
    | '/simulation'
    | '/threat-monitoring'
    | '/verify'
    | '/verify-status'
    | '/dashboard/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  CitizenRoute: typeof CitizenRoute
  CommandCenterRoute: typeof CommandCenterRoute
  EventsRoute: typeof EventsRoute
  FaceScanRoute: typeof FaceScanRoute
  FraudDetectionRoute: typeof FraudDetectionRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SimulationRoute: typeof SimulationRoute
  ThreatMonitoringRoute: typeof ThreatMonitoringRoute
  VerifyRoute: typeof VerifyRoute
  VerifyStatusRoute: typeof VerifyStatusRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-status': {
      id: '/verify-status'
      path: '/verify-status'
      fullPath: '/verify-status'
      preLoaderRoute: typeof VerifyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-monitoring': {
      id: '/threat-monitoring'
      path: '/threat-monitoring'
      fullPath: '/threat-monitoring'
      preLoaderRoute: typeof ThreatMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-detection': {
      id: '/fraud-detection'
      path: '/fraud-detection'
      fullPath: '/fraud-detection'
      preLoaderRoute: typeof FraudDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-scan': {
      id: '/face-scan'
      path: '/face-scan'
      fullPath: '/face-scan'
      preLoaderRoute: typeof FaceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-gateway': {
      id: '/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  CitizenRoute: CitizenRoute,
  CommandCenterRoute: CommandCenterRoute,
  EventsRoute: EventsRoute,
  FaceScanRoute: FaceScanRoute,
  FraudDetectionRoute: FraudDetectionRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SimulationRoute: SimulationRoute,
  ThreatMonitoringRoute: ThreatMonitoringRoute,
  VerifyRoute: VerifyRoute,
  VerifyStatusRoute: VerifyStatusRoute,
  DashboardRoleRoute: DashboardRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
